# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
#
service: short-bot

provider:

  name: aws

  runtime: nodejs10.x

  region: eu-west-2

functions:

  shortbot:

    handler: handler.shortbot

    events:

      - http:

          path: short-bot

          method: post

          cors: true
